### ISSUE TITLE
Providing full path to json-file can cause the file to be re-written

### ISSUE THREAD

**Issue by KarstenTonnesenSeluxit** [Wappsto/wappsto-python#127]
If you provide a full path to the input json file like this:

`service = wappsto.Wappsto(json_file_name='/opt/wappsto/8968ff7c-dead-44e5-83c3-18afb7b309c5/8968ff7c-dead-44e5-83c3-18afb7b309c5.json')`

It will work once, but afterwards the file will be identical to the backup file in 'saved_instances' folder - meaning all certificates, uuids, etc will have been deleted.

**Comment by tacozMacleo** [comment]
Was it after a reset it happens?
And had you remembered to disable rapid-prototype-runner on your porcupine?
If not it will be overwritten with the published version from wappsto.

**Comment by KarstenTonnesenSeluxit** [comment]
Rapid-prototype-runner was disabled, I war running wappsto manually from the commandline interface.
Giving a full oath to the json-file it could only work once - eg after first connect the json is now invalid.
Giving the "normal from the same foler" filename then it does not happen.

**Comment by tacozMacleo** [comment]
The Problem seems to be coming from here:
https://github.com/Wappsto/wappsto-python/blob/76dcc90dc5e564603a5dc8e67b7c718ca563c335/wappsto/data_operation/data_manager.py#L142-L151
It saves in the old data format into the `saved_instances` folder, which on the next load overloads the location you are given it:
https://github.com/Wappsto/wappsto-python/blob/76dcc90dc5e564603a5dc8e67b7c718ca563c335/wappsto/data_operation/data_manager.py#L47-L50

So a quick fix will be to update the data format to use the new one.
The right way, will be to find where it overwrite the json-file. But that still eludes me.

**Comment by tacozMacleo** [comment]
The problem lies here:
https://github.com/Wappsto/wappsto-python/blob/76dcc90dc5e564603a5dc8e67b7c718ca563c335/wappsto/data_operation/data_manager.py#L148
The value: `self.json_file_name` is the json file name input.
This tickers a side ability in the `os.path.join`-function
```
join(a, *p)
    Join two or more pathname components, inserting '/' as needed.
    If any component is an absolute path, all previous path components
    will be discarded.  An empty last part will result in a path that
    ends with a separator.
```
